# Generated by Django 4.2.19 on 2025-03-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalRequest',
        ),
    ]
